url: https://delmehr.github.io/dariush/
timezone: Iran/Tehran
permalink: /:year/:month/:day/:title.html
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

sass:
    sass_dir: dariush/assets/css/_sass
    style: :compressed

collections:
    projects:
        output: true
        

exclude: [vendor]


  
